"""baseline full schema

Revision ID: 69da20d1e47c
Revises: 
Create Date: 2026-07-17 15:44:46.276489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69da20d1e47c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attention_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('focus_topic', sa.String(length=256), nullable=True),
    sa.Column('recent_topics', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('suggestion', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attention_states_thread_id'), 'attention_states', ['thread_id'], unique=False)
    op.create_table('capabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('descriptor_hash', sa.String(length=32), nullable=True),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capabilities_capability_id'), 'capabilities', ['capability_id'], unique=True)
    op.create_index(op.f('ix_capabilities_state'), 'capabilities', ['state'], unique=False)
    op.create_table('capability_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('goal_summary', sa.String(length=256), nullable=True),
    sa.Column('missing_capability_type', sa.String(length=64), nullable=True),
    sa.Column('candidates', sa.JSON(), nullable=True),
    sa.Column('risk_scores', sa.JSON(), nullable=True),
    sa.Column('selected_candidate', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('install_plan', sa.JSON(), nullable=True),
    sa.Column('smoke_result', sa.JSON(), nullable=True),
    sa.Column('capability_id', sa.String(length=128), nullable=True),
    sa.Column('lesson_memory_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_plans_status'), 'capability_plans', ['status'], unique=False)
    op.create_table('content_provenance_refs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_type', 'owner_id', 'source_type', 'source_id', name='uq_provenance_owner_source')
    )
    op.create_index('ix_provenance_source', 'content_provenance_refs', ['source_type', 'source_id'], unique=False)
    op.create_table('core_memory_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('block_name', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_memory_ids', sa.JSON(), nullable=False),
    sa.Column('projection_version', sa.Integer(), nullable=False),
    sa.Column('record_versions', sa.JSON(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_memory_blocks_block_name'), 'core_memory_blocks', ['block_name'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_path', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=True)
    op.create_table('epoch_checkpoints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('epoch_id', sa.String(length=36), nullable=False),
    sa.Column('current_goal', sa.Text(), nullable=True),
    sa.Column('completed_milestones', sa.JSON(), nullable=True),
    sa.Column('open_loops', sa.JSON(), nullable=True),
    sa.Column('active_constraints', sa.JSON(), nullable=True),
    sa.Column('current_decisions', sa.JSON(), nullable=True),
    sa.Column('referenced_artifacts', sa.JSON(), nullable=True),
    sa.Column('relevant_entities', sa.JSON(), nullable=True),
    sa.Column('latest_verified_tool_states', sa.JSON(), nullable=True),
    sa.Column('source_segment_ids', sa.JSON(), nullable=True),
    sa.Column('source_hashes', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('epoch_id', 'version', name='uq_epoch_checkpoint_epoch_version')
    )
    op.create_index(op.f('ix_epoch_checkpoints_epoch_id'), 'epoch_checkpoints', ['epoch_id'], unique=False)
    op.create_table('forget_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operation_key', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('selector_type', sa.String(length=32), nullable=False),
    sa.Column('selector_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('shielded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('legacy_request_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('requested', 'shielded', 'cascading', 'verifying', 'purge_ready', 'purging', 'purged', 'verified', 'verified_with_coarse_purge', 'legacy_unverifiable', 'failed_retryable', 'deadletter', 'shielded_deadletter')", name='ck_forget_op_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_key')
    )
    op.create_table('forget_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('tombstone', sa.String(length=256), nullable=False),
    sa.Column('saga_state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forget_requests_memory_id'), 'forget_requests', ['memory_id'], unique=False)
    op.create_table('memory_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('proposal_id', sa.String(length=128), nullable=False),
    sa.Column('source_event_ids', sa.JSON(), nullable=True),
    sa.Column('memory_type', sa.String(length=64), nullable=True),
    sa.Column('canonical_key', sa.String(length=256), nullable=True),
    sa.Column('scope_type', sa.String(length=32), nullable=True),
    sa.Column('scope_id', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('structured_value', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('trust_level', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('stability', sa.String(length=32), nullable=True),
    sa.Column('stability_score', sa.Float(), nullable=True),
    sa.Column('proposed_operation', sa.String(length=32), nullable=True),
    sa.Column('gate_decision', sa.String(length=32), nullable=True),
    sa.Column('gate_reason', sa.Text(), nullable=True),
    sa.Column('blocked_reason', sa.String(length=64), nullable=True),
    sa.Column('final_operation', sa.String(length=32), nullable=True),
    sa.Column('final_memory_id', sa.String(length=36), nullable=True),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('extractor_name', sa.String(length=64), nullable=True),
    sa.Column('extractor_version', sa.String(length=32), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('normalized_payload', sa.JSON(), nullable=True),
    sa.Column('source_turn_id', sa.String(length=36), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('proposal_index', sa.Integer(), nullable=True),
    sa.Column('execution_mode', sa.String(length=32), nullable=False),
    sa.Column('retention_policy', sa.String(length=32), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('durable', sa.Boolean(), nullable=False),
    sa.Column('source_turn_record_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingestion_run_id', 'proposal_index', name='uq_memory_proposal_run_index')
    )
    op.create_index(op.f('ix_memory_proposals_idempotency_key'), 'memory_proposals', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_memory_proposals_proposal_id'), 'memory_proposals', ['proposal_id'], unique=True)
    op.create_table('memory_recall_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('route', sa.String(length=32), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('fused_score', sa.Float(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=64), nullable=False),
    sa.Column('token_cost', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_recall_candidates_memory_id'), 'memory_recall_candidates', ['memory_id'], unique=False)
    op.create_index(op.f('ix_memory_recall_candidates_run_id'), 'memory_recall_candidates', ['run_id'], unique=False)
    op.create_table('memory_recall_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('request_query', sa.Text(), nullable=False),
    sa.Column('scope_context', sa.JSON(), nullable=False),
    sa.Column('routes_executed', sa.JSON(), nullable=False),
    sa.Column('token_budget', sa.Integer(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('total_latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_recall_runs_trace_id'), 'memory_recall_runs', ['trace_id'], unique=False)
    op.create_table('memory_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('memory_type', sa.String(length=64), nullable=False),
    sa.Column('canonical_key', sa.String(length=256), nullable=True),
    sa.Column('cardinality', sa.String(length=16), nullable=True),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_value', sa.JSON(), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('validity_state', sa.String(length=32), nullable=False),
    sa.Column('trust_level', sa.String(length=32), nullable=False),
    sa.Column('stability', sa.String(length=32), nullable=False),
    sa.Column('sensitivity', sa.String(length=32), nullable=True),
    sa.Column('content_hash', sa.String(length=32), nullable=True),
    sa.Column('structured_value_hash', sa.String(length=32), nullable=True),
    sa.Column('stability_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('reinforce_count', sa.Integer(), nullable=False),
    sa.Column('source_event_id', sa.String(length=36), nullable=True),
    sa.Column('lineage', sa.String(length=128), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('memory_key', sa.String(length=128), nullable=True),
    sa.Column('revision_num', sa.Integer(), nullable=False),
    sa.Column('supersedes', sa.String(length=36), nullable=True),
    sa.Column('superseded_by', sa.String(length=36), nullable=True),
    sa.Column('created_from', sa.String(length=36), nullable=True),
    sa.Column('revision_of', sa.String(length=36), nullable=True),
    sa.Column('merged_from', sa.JSON(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_policy', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_reinforced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_records_canonical_key'), 'memory_records', ['canonical_key'], unique=False)
    op.create_index(op.f('ix_memory_records_lifecycle_state'), 'memory_records', ['lifecycle_state'], unique=False)
    op.create_index(op.f('ix_memory_records_memory_key'), 'memory_records', ['memory_key'], unique=False)
    op.create_index(op.f('ix_memory_records_memory_type'), 'memory_records', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memory_records_scope_type'), 'memory_records', ['scope_type'], unique=False)
    op.create_table('outbox_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=128), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('claim_token', sa.String(length=36), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminal_reason', sa.String(length=64), nullable=True),
    sa.Column('terminal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_status', sa.String(length=32), nullable=True),
    sa.Column('migration_batch_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_claim', 'outbox_jobs', ['status', 'available_at', 'lease_expires_at'], unique=False)
    op.create_index(op.f('ix_outbox_jobs_job_type'), 'outbox_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_outbox_jobs_operation_id'), 'outbox_jobs', ['operation_id'], unique=True)
    op.create_index(op.f('ix_outbox_jobs_status'), 'outbox_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_jobs_trace_id'), 'outbox_jobs', ['trace_id'], unique=False)
    op.create_index('ix_outbox_migration_batch', 'outbox_jobs', ['migration_batch_id'], unique=False)
    op.create_table('retrieval_index_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('index_version', sa.BigInteger(), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=True),
    sa.Column('epoch_id', sa.String(length=36), nullable=True),
    sa.Column('segment_id', sa.String(length=36), nullable=True),
    sa.Column('memory_record_id', sa.String(length=36), nullable=True),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.String(length=128), nullable=True),
    sa.Column('canonical_key', sa.String(length=256), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=True),
    sa.Column('validity_state', sa.String(length=32), nullable=True),
    sa.Column('retrieval_tier', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('search_text', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_source_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_source_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('is_searchable', sa.Boolean(), nullable=False),
    sa.CheckConstraint("retrieval_tier IN ('hot','warm','cold')", name='ck_retrieval_entry_tier'),
    sa.CheckConstraint("source_type IN ('memory_record','segment_summary','epoch_checkpoint')", name='ck_retrieval_entry_src'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'source_version', 'index_version', name='uq_retrieval_entry_src_ver_gen')
    )
    op.create_index('ix_retrieval_entry_active', 'retrieval_index_entries', ['index_version', 'is_current', 'source_type'], unique=False)
    op.create_index('ix_retrieval_entry_scope', 'retrieval_index_entries', ['scope_type', 'scope_id'], unique=False)
    op.create_index('ix_retrieval_entry_thread', 'retrieval_index_entries', ['thread_id'], unique=False)
    op.create_index('ix_retrieval_entry_tier', 'retrieval_index_entries', ['retrieval_tier'], unique=False)
    op.create_index('uq_retrieval_entry_current', 'retrieval_index_entries', ['index_version', 'source_type', 'source_id'], unique=True, postgresql_where=sa.text('is_current IS TRUE'), sqlite_where=sa.text('is_current = 1'))
    op.create_table('retrieval_index_generations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('index_version', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('build_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('build_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_cutoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('backfill_done', sa.Boolean(), nullable=False),
    sa.CheckConstraint("status IN ('building','active','retired','failed')", name='ck_retrieval_gen_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_version')
    )
    op.create_table('retrieval_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segment_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('decisions', sa.JSON(), nullable=True),
    sa.Column('open_loops', sa.JSON(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('artifacts', sa.JSON(), nullable=True),
    sa.Column('important_tool_results', sa.JSON(), nullable=True),
    sa.Column('source_turn_ids', sa.JSON(), nullable=True),
    sa.Column('source_event_ids', sa.JSON(), nullable=True),
    sa.Column('active_constraints', sa.JSON(), nullable=True),
    sa.Column('unresolved_failures', sa.JSON(), nullable=True),
    sa.Column('omitted_artifact_refs', sa.JSON(), nullable=True),
    sa.Column('source_turn_range', sa.JSON(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('summary_version', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id', 'summary_version', name='uq_segment_summary_segment_version')
    )
    op.create_index(op.f('ix_segment_summaries_segment_id'), 'segment_summaries', ['segment_id'], unique=False)
    op.create_table('selfdev_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('source_event_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selfdev_requests_trace_id'), 'selfdev_requests', ['trace_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_event_id', sa.String(length=36), nullable=True),
    sa.Column('thread_id', sa.String(length=36), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('next_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_next_check_at'), 'tasks', ['next_check_at'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_tasks_thread_id'), 'tasks', ['thread_id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('ref', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('turn_record_id', sa.String(length=36), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('tool_call_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turn_record_id', 'tool_call_id', name='uq_artifact_turn_tool')
    )
    op.create_index(op.f('ix_artifacts_ref'), 'artifacts', ['ref'], unique=True)
    op.create_index(op.f('ix_artifacts_thread_id'), 'artifacts', ['thread_id'], unique=False)
    op.create_table('capability_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('descriptor_hash', sa.String(length=32), nullable=False),
    sa.Column('tool_list_hash', sa.String(length=32), nullable=True),
    sa.Column('smoke_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_versions_capability_id'), 'capability_versions', ['capability_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_table('context_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('stable_prefix_hash', sa.String(length=32), nullable=False),
    sa.Column('context_items', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('epoch_id', sa.String(length=36), nullable=True),
    sa.Column('segment_id', sa.String(length=36), nullable=True),
    sa.Column('turn_sequence', sa.BigInteger(), nullable=True),
    sa.Column('retention', sa.String(length=32), nullable=False),
    sa.Column('token_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_snapshots_thread_id'), 'context_snapshots', ['thread_id'], unique=False)
    op.create_index(op.f('ix_context_snapshots_trace_id'), 'context_snapshots', ['trace_id'], unique=False)
    op.create_index('ix_snapshots_thread_retention', 'context_snapshots', ['thread_id', 'retention'], unique=False)
    op.create_index('ix_snapshots_trace', 'context_snapshots', ['trace_id', 'thread_id'], unique=False)
    op.create_table('epochs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('epoch_no', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_turn_sequence', sa.BigInteger(), nullable=True),
    sa.Column('end_turn_sequence', sa.BigInteger(), nullable=True),
    sa.Column('checkpoint_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'epoch_no', name='uq_epoch_thread_no')
    )
    op.create_index(op.f('ix_epochs_thread_id'), 'epochs', ['thread_id'], unique=False)
    op.create_index('ix_epochs_thread_status', 'epochs', ['thread_id', 'status'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=True),
    sa.Column('turn_event_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index('ix_events_thread_created', 'events', ['thread_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_events_thread_id'), 'events', ['thread_id'], unique=False)
    op.create_index(op.f('ix_events_trace_id'), 'events', ['trace_id'], unique=False)
    op.create_index('ix_events_turn_order', 'events', ['thread_id', 'turn_id', 'turn_event_index'], unique=False)
    op.create_table('forget_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('forget_operation_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('dependency_type', sa.String(length=32), nullable=True),
    sa.Column('batch_no', sa.Integer(), nullable=False),
    sa.Column('cursor_lane', sa.String(length=32), nullable=True),
    sa.Column('cursor_start_json', sa.JSON(), nullable=True),
    sa.Column('cursor_end_json', sa.JSON(), nullable=True),
    sa.Column('cutoff', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('action_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['forget_operation_id'], ['forget_operations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forget_operation_id', 'stage', 'dependency_type', 'batch_no', name='uq_batch_op_stage_type_no')
    )
    op.create_table('forget_selector_manifests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('forget_operation_id', sa.String(length=36), nullable=False),
    sa.Column('selector_type', sa.String(length=32), nullable=False),
    sa.Column('selector_payload', sa.JSON(), nullable=False),
    sa.Column('selector_payload_hash', sa.String(length=64), nullable=False),
    sa.Column('cutoff_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['forget_operation_id'], ['forget_operations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forget_operation_id', 'selector_payload_hash', name='uq_selector_manifest_op_payload')
    )
    op.create_table('forget_shields',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('forget_operation_id', sa.String(length=36), nullable=False),
    sa.Column('selector_type', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('canonical_key', sa.String(length=256), nullable=True),
    sa.Column('value_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('thread_id', sa.String(length=36), nullable=True),
    sa.Column('time_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope_type', sa.String(length=32), nullable=True),
    sa.Column('scope_id', sa.String(length=128), nullable=True),
    sa.Column('all_user_data', sa.Boolean(), nullable=False),
    sa.Column('cutoff_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('normalized_shield_key', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['forget_operation_id'], ['forget_operations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forget_operation_id', 'normalized_shield_key', name='uq_shield_op_norm_key')
    )
    op.create_table('forget_stage_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('forget_operation_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('outbox_job_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('execution_token', sa.String(length=64), nullable=True),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['forget_operation_id'], ['forget_operations.id'], ),
    sa.ForeignKeyConstraint(['outbox_job_id'], ['outbox_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outbox_job_id')
    )
    op.create_table('forget_targets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('forget_operation_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('source_version', sa.String(length=64), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('scope_type', sa.String(length=32), nullable=True),
    sa.Column('scope_id', sa.String(length=128), nullable=True),
    sa.Column('canonical_key', sa.String(length=256), nullable=True),
    sa.Column('value_hash', sa.String(length=64), nullable=True),
    sa.Column('batch_no', sa.Integer(), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['forget_operation_id'], ['forget_operations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forget_operation_id', 'target_type', 'target_id', name='uq_target_op_type_id')
    )
    op.create_table('forget_tombstones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('forget_operation_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_key', sa.String(length=256), nullable=True),
    sa.Column('scope_type', sa.String(length=32), nullable=True),
    sa.Column('scope_id', sa.String(length=128), nullable=True),
    sa.Column('value_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('fingerprint_key_version', sa.Integer(), nullable=True),
    sa.Column('block_visibility', sa.Boolean(), nullable=False),
    sa.Column('block_reingestion', sa.Boolean(), nullable=False),
    sa.Column('content_purged', sa.Boolean(), nullable=False),
    sa.Column('allow_audit_read', sa.Boolean(), nullable=False),
    sa.Column('source_event_id', sa.String(length=36), nullable=True),
    sa.Column('source_turn_record_id', sa.String(length=36), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['forget_operation_id'], ['forget_operations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forget_operation_id', 'target_type', 'target_id', name='uq_tombstone_op_type_id')
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('input_preview', sa.Text(), nullable=True),
    sa.Column('output_preview', sa.Text(), nullable=True),
    sa.Column('estimated_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('safe_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('actual_prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('actual_completion_tokens', sa.Integer(), nullable=True),
    sa.Column('token_source', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_thread_id'), 'llm_calls', ['thread_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_trace_id'), 'llm_calls', ['trace_id'], unique=False)
    op.create_table('mcp_install_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('server_name', sa.String(length=256), nullable=False),
    sa.Column('package_ref', sa.String(length=256), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('transport', sa.String(length=32), nullable=False),
    sa.Column('declared_tools', sa.JSON(), nullable=False),
    sa.Column('sandbox_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_install_records_capability_id'), 'mcp_install_records', ['capability_id'], unique=False)
    op.create_table('memory_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('source_event_id', sa.String(length=36), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('trust_level', sa.String(length=32), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.Column('content_span', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memory_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_evidence_memory_id'), 'memory_evidence', ['memory_id'], unique=False)
    op.create_table('memory_lineage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('predecessor_id', sa.String(length=36), nullable=False),
    sa.Column('successor_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('proposal_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['predecessor_id'], ['memory_records.id'], ),
    sa.ForeignKeyConstraint(['successor_id'], ['memory_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_lineage_predecessor_id'), 'memory_lineage', ['predecessor_id'], unique=False)
    op.create_index(op.f('ix_memory_lineage_successor_id'), 'memory_lineage', ['successor_id'], unique=False)
    op.create_table('memory_maintenance_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_type', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.String(length=128), nullable=True),
    sa.Column('outbox_job_id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('execution_token', sa.String(length=128), nullable=True),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('failure_attempt_count', sa.Integer(), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cutoff_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cursor_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor_id', sa.String(length=36), nullable=True),
    sa.Column('plan_hash', sa.String(length=64), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('applied_count', sa.Integer(), nullable=False),
    sa.Column('skipped_stale_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['outbox_job_id'], ['outbox_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id', name='uq_maintenance_run_operation'),
    sa.UniqueConstraint('outbox_job_id', name='uq_maintenance_run_outbox_job')
    )
    op.create_index('ix_maintenance_run_scope_status', 'memory_maintenance_runs', ['scope_type', 'status'], unique=False)
    op.create_index(op.f('ix_memory_maintenance_runs_status'), 'memory_maintenance_runs', ['status'], unique=False)
    op.create_table('patch_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('target_file', sa.String(length=512), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('requires_schema_change', sa.Boolean(), nullable=False),
    sa.Column('safe_delete_scope', sa.String(length=64), nullable=True),
    sa.Column('not_allowed_yet', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['selfdev_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patch_operations_request_id'), 'patch_operations', ['request_id'], unique=False)
    op.create_table('retention_cleanup_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outbox_job_id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=128), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('policy_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('execution_token', sa.String(length=64), nullable=True),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('current_lane', sa.String(length=64), nullable=True),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scanned_count', sa.Integer(), nullable=False),
    sa.Column('scrubbed_count', sa.Integer(), nullable=False),
    sa.Column('deleted_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['outbox_job_id'], ['outbox_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id', name='uq_retention_run_operation'),
    sa.UniqueConstraint('outbox_job_id', name='uq_retention_run_outbox_job')
    )
    op.create_index(op.f('ix_retention_cleanup_runs_status'), 'retention_cleanup_runs', ['status'], unique=False)
    op.create_index('ix_retention_run_status', 'retention_cleanup_runs', ['status'], unique=False)
    op.create_table('retrieval_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['retrieval_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_candidates_run_id'), 'retrieval_candidates', ['run_id'], unique=False)
    op.create_table('retrieval_index_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outbox_job_id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('execution_token', sa.String(length=128), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('failure_attempt_count', sa.Integer(), nullable=False),
    sa.Column('index_version', sa.BigInteger(), nullable=False),
    sa.Column('batch_cursor', sa.JSON(), nullable=True),
    sa.Column('indexed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_stale_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['outbox_job_id'], ['outbox_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id', name='uq_retrieval_run_operation'),
    sa.UniqueConstraint('outbox_job_id', name='uq_retrieval_run_outbox_job')
    )
    op.create_index(op.f('ix_retrieval_index_runs_status'), 'retrieval_index_runs', ['status'], unique=False)
    op.create_index('ix_retrieval_run_status', 'retrieval_index_runs', ['status'], unique=False)
    op.create_table('retrieval_index_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entry_id', sa.String(length=36), nullable=False),
    sa.Column('index_version', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('token_kind', sa.String(length=16), nullable=False),
    sa.Column('term_frequency', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['retrieval_index_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'token', name='uq_retrieval_token_entry')
    )
    op.create_index('ix_retrieval_token_entry', 'retrieval_index_tokens', ['entry_id'], unique=False)
    op.create_index('ix_retrieval_token_lookup', 'retrieval_index_tokens', ['index_version', 'token', 'entry_id'], unique=False)
    op.create_table('turn_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=False),
    sa.Column('turn_sequence', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_event_id', sa.String(length=36), nullable=True),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('epoch_id', sa.String(length=36), nullable=True),
    sa.Column('segment_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'turn_id', name='uq_turn_record_thread_turn')
    )
    op.create_index('ix_turn_records_thread_sequence', 'turn_records', ['thread_id', 'turn_sequence'], unique=False)
    op.create_index('ix_turn_records_thread_status', 'turn_records', ['thread_id', 'status'], unique=False)
    op.create_table('working_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('epoch_id', sa.String(length=36), nullable=True),
    sa.Column('current_objective', sa.Text(), nullable=True),
    sa.Column('open_loops', sa.JSON(), nullable=False),
    sa.Column('active_constraints', sa.JSON(), nullable=False),
    sa.Column('pending_approvals', sa.JSON(), nullable=False),
    sa.Column('artifact_refs', sa.JSON(), nullable=False),
    sa.Column('verified_tool_states', sa.JSON(), nullable=False),
    sa.Column('uncommitted_side_effects', sa.JSON(), nullable=False),
    sa.Column('running_tool_state', sa.JSON(), nullable=False),
    sa.Column('applied_idempotency_keys', sa.JSON(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', name='uq_working_state_thread')
    )
    op.create_table('epoch_compaction_inputs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('epoch_id', sa.String(length=36), nullable=False),
    sa.Column('boundary_turn_sequence', sa.BigInteger(), nullable=False),
    sa.Column('working_state_version', sa.Integer(), nullable=False),
    sa.Column('current_objective', sa.Text(), nullable=True),
    sa.Column('open_loops', sa.JSON(), nullable=False),
    sa.Column('active_constraints', sa.JSON(), nullable=False),
    sa.Column('artifact_refs', sa.JSON(), nullable=False),
    sa.Column('verified_tool_states', sa.JSON(), nullable=False),
    sa.Column('source_segment_ids', sa.JSON(), nullable=False),
    sa.Column('source_hashes', sa.JSON(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('checkpoint_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['epoch_id'], ['epochs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('epoch_id', 'snapshot_hash', 'checkpoint_version', name='uq_epoch_input_epoch_hash_version')
    )
    op.create_index(op.f('ix_epoch_compaction_inputs_epoch_id'), 'epoch_compaction_inputs', ['epoch_id'], unique=False)
    op.create_table('forget_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('forget_operation_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('dependency_type', sa.String(length=32), nullable=False),
    sa.Column('dependency_id', sa.String(length=36), nullable=False),
    sa.Column('discovery_batch_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['forget_operation_id'], ['forget_operations.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['forget_targets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forget_operation_id', 'dependency_type', 'dependency_id', name='uq_dep_op_type_id')
    )
    op.create_table('memory_ingestion_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_turn_record_id', sa.String(length=36), nullable=False),
    sa.Column('extractor_name', sa.String(length=64), nullable=False),
    sa.Column('extractor_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('execution_token', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proposal_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_turn_record_id'], ['turn_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_turn_record_id', 'extractor_name', 'extractor_version', name='uq_ingestion_run_source_extractor')
    )
    op.create_table('memory_maintenance_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('batch_no', sa.BigInteger(), nullable=False),
    sa.Column('candidate_lane', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('lane_cursor_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lane_cursor_id', sa.String(length=36), nullable=True),
    sa.Column('cursor_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor_start_id', sa.String(length=36), nullable=True),
    sa.Column('cursor_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor_end_id', sa.String(length=36), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('plan_hash', sa.String(length=64), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('action_count', sa.Integer(), nullable=False),
    sa.Column('applied_count', sa.Integer(), nullable=False),
    sa.Column('skipped_stale_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['memory_maintenance_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'batch_no', name='uq_maintenance_batch_run_no')
    )
    op.create_index('ix_maintenance_batch_run_status', 'memory_maintenance_batches', ['run_id', 'status'], unique=False)
    op.create_index(op.f('ix_memory_maintenance_batches_status'), 'memory_maintenance_batches', ['status'], unique=False)
    op.create_table('retention_cleanup_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('lane', sa.String(length=64), nullable=False),
    sa.Column('batch_no', sa.BigInteger(), nullable=False),
    sa.Column('cursor_start_json', sa.JSON(), nullable=False),
    sa.Column('cursor_end_json', sa.JSON(), nullable=True),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scanned_count', sa.Integer(), nullable=False),
    sa.Column('scrubbed_count', sa.Integer(), nullable=False),
    sa.Column('deleted_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['retention_cleanup_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'lane', 'batch_no', name='uq_retention_batch_run_lane_no')
    )
    op.create_index('ix_retention_batch_run_status', 'retention_cleanup_batches', ['run_id', 'status'], unique=False)
    op.create_index(op.f('ix_retention_cleanup_batches_status'), 'retention_cleanup_batches', ['status'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('epoch_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('segment_no', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('start_turn_sequence', sa.BigInteger(), nullable=False),
    sa.Column('end_turn_sequence', sa.BigInteger(), nullable=True),
    sa.Column('source_hash', sa.String(length=64), nullable=True),
    sa.Column('summary_id', sa.String(length=36), nullable=True),
    sa.Column('pending_seal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sealed_by_turn', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status <> 'sealed' OR summary_id IS NOT NULL", name='ck_segment_sealed_requires_summary'),
    sa.CheckConstraint('end_turn_sequence IS NULL OR end_turn_sequence >= start_turn_sequence', name='ck_segment_turn_range'),
    sa.CheckConstraint('start_turn_sequence IS NOT NULL', name='ck_segment_start_turn'),
    sa.ForeignKeyConstraint(['epoch_id'], ['epochs.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('epoch_id', 'segment_no', name='uq_segment_epoch_no')
    )
    op.create_index(op.f('ix_segments_epoch_id'), 'segments', ['epoch_id'], unique=False)
    op.create_index('ix_segments_epoch_status', 'segments', ['epoch_id', 'status'], unique=False)
    op.create_table('checkpoint_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('epoch_id', sa.String(length=36), nullable=False),
    sa.Column('epoch_compaction_input_id', sa.String(length=36), nullable=False),
    sa.Column('outbox_job_id', sa.String(length=36), nullable=False),
    sa.Column('boundary_hash', sa.String(length=64), nullable=False),
    sa.Column('checkpoint_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('execution_token', sa.String(length=128), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['epoch_compaction_input_id'], ['epoch_compaction_inputs.id'], ),
    sa.ForeignKeyConstraint(['epoch_id'], ['epochs.id'], ),
    sa.ForeignKeyConstraint(['outbox_job_id'], ['outbox_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('epoch_id', 'boundary_hash', 'checkpoint_version', name='uq_checkpoint_epoch_hash_version'),
    sa.UniqueConstraint('outbox_job_id', name='uq_checkpoint_run_outbox_job')
    )
    op.create_index('ix_checkpoint_epoch_status', 'checkpoint_runs', ['epoch_id', 'status'], unique=False)
    op.create_index(op.f('ix_checkpoint_runs_epoch_id'), 'checkpoint_runs', ['epoch_id'], unique=False)
    op.create_table('compaction_inputs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('start_turn_sequence', sa.BigInteger(), nullable=False),
    sa.Column('end_turn_sequence', sa.BigInteger(), nullable=False),
    sa.Column('turn_manifest', sa.JSON(), nullable=False),
    sa.Column('event_manifest', sa.JSON(), nullable=False),
    sa.Column('working_state_version', sa.Integer(), nullable=False),
    sa.Column('working_state_snapshot', sa.JSON(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('summary_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id', 'source_hash', 'summary_version', name='uq_compaction_input_segment_hash_version')
    )
    op.create_index(op.f('ix_compaction_inputs_segment_id'), 'compaction_inputs', ['segment_id'], unique=False)
    op.create_table('forget_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('forget_operation_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('dependency_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('batch_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('expected_version', sa.Integer(), nullable=True),
    sa.Column('before_hash', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dependency_id'], ['forget_dependencies.id'], ),
    sa.ForeignKeyConstraint(['forget_operation_id'], ['forget_operations.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['forget_targets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('memory_maintenance_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('action_sequence', sa.BigInteger(), nullable=False),
    sa.Column('source_input_ids', sa.JSON(), nullable=True),
    sa.Column('operation_group_id', sa.String(length=64), nullable=True),
    sa.Column('subject_memory_record_id', sa.String(length=36), nullable=True),
    sa.Column('related_record_ids', sa.JSON(), nullable=True),
    sa.Column('canonical_key', sa.String(length=256), nullable=True),
    sa.Column('scope_type', sa.String(length=32), nullable=True),
    sa.Column('scope_id', sa.String(length=128), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('expected_record_version', sa.Integer(), nullable=True),
    sa.Column('preconditions', sa.JSON(), nullable=True),
    sa.Column('after_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['memory_maintenance_batches.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['memory_maintenance_runs.id'], ),
    sa.ForeignKeyConstraint(['subject_memory_record_id'], ['memory_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'action_sequence', name='uq_maintenance_action_batch_seq'),
    sa.UniqueConstraint('idempotency_key', name='uq_maintenance_action_idem')
    )
    op.create_index('ix_maintenance_action_batch', 'memory_maintenance_actions', ['batch_id'], unique=False)
    op.create_index('ix_maintenance_action_run', 'memory_maintenance_actions', ['run_id'], unique=False)
    op.create_index(op.f('ix_memory_maintenance_actions_status'), 'memory_maintenance_actions', ['status'], unique=False)
    op.create_table('memory_maintenance_inputs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('input_sequence', sa.BigInteger(), nullable=False),
    sa.Column('memory_record_id', sa.String(length=36), nullable=False),
    sa.Column('input_role', sa.String(length=16), nullable=False),
    sa.Column('record_version', sa.Integer(), nullable=False),
    sa.Column('record_state_hash', sa.String(length=64), nullable=True),
    sa.Column('decision_hash', sa.String(length=64), nullable=True),
    sa.Column('user_required_protected', sa.Boolean(), nullable=False),
    sa.Column('user_required_source_ids', sa.JSON(), nullable=True),
    sa.Column('canonical_key', sa.String(length=256), nullable=True),
    sa.Column('scope_type', sa.String(length=32), nullable=True),
    sa.Column('scope_id', sa.String(length=128), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['memory_maintenance_batches.id'], ),
    sa.ForeignKeyConstraint(['memory_record_id'], ['memory_records.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['memory_maintenance_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'input_sequence', name='uq_maintenance_input_batch_seq'),
    sa.UniqueConstraint('batch_id', 'memory_record_id', name='uq_maintenance_input_batch_record')
    )
    op.create_index('ix_maintenance_input_batch', 'memory_maintenance_inputs', ['batch_id'], unique=False)
    op.create_table('compaction_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('compaction_input_id', sa.String(length=36), nullable=False),
    sa.Column('outbox_job_id', sa.String(length=36), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('summary_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('execution_token', sa.String(length=128), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compaction_input_id'], ['compaction_inputs.id'], ),
    sa.ForeignKeyConstraint(['outbox_job_id'], ['outbox_jobs.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outbox_job_id', name='uq_compaction_run_outbox_job'),
    sa.UniqueConstraint('segment_id', 'source_hash', 'summary_version', name='uq_compaction_segment_hash_version')
    )
    op.create_index(op.f('ix_compaction_runs_segment_id'), 'compaction_runs', ['segment_id'], unique=False)
    op.create_index('ix_compaction_segment_status', 'compaction_runs', ['segment_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_compaction_segment_status', table_name='compaction_runs')
    op.drop_index(op.f('ix_compaction_runs_segment_id'), table_name='compaction_runs')
    op.drop_table('compaction_runs')
    op.drop_index('ix_maintenance_input_batch', table_name='memory_maintenance_inputs')
    op.drop_table('memory_maintenance_inputs')
    op.drop_index(op.f('ix_memory_maintenance_actions_status'), table_name='memory_maintenance_actions')
    op.drop_index('ix_maintenance_action_run', table_name='memory_maintenance_actions')
    op.drop_index('ix_maintenance_action_batch', table_name='memory_maintenance_actions')
    op.drop_table('memory_maintenance_actions')
    op.drop_table('forget_actions')
    op.drop_index(op.f('ix_compaction_inputs_segment_id'), table_name='compaction_inputs')
    op.drop_table('compaction_inputs')
    op.drop_index(op.f('ix_checkpoint_runs_epoch_id'), table_name='checkpoint_runs')
    op.drop_index('ix_checkpoint_epoch_status', table_name='checkpoint_runs')
    op.drop_table('checkpoint_runs')
    op.drop_index('ix_segments_epoch_status', table_name='segments')
    op.drop_index(op.f('ix_segments_epoch_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_retention_cleanup_batches_status'), table_name='retention_cleanup_batches')
    op.drop_index('ix_retention_batch_run_status', table_name='retention_cleanup_batches')
    op.drop_table('retention_cleanup_batches')
    op.drop_index(op.f('ix_memory_maintenance_batches_status'), table_name='memory_maintenance_batches')
    op.drop_index('ix_maintenance_batch_run_status', table_name='memory_maintenance_batches')
    op.drop_table('memory_maintenance_batches')
    op.drop_table('memory_ingestion_runs')
    op.drop_table('forget_dependencies')
    op.drop_index(op.f('ix_epoch_compaction_inputs_epoch_id'), table_name='epoch_compaction_inputs')
    op.drop_table('epoch_compaction_inputs')
    op.drop_table('working_states')
    op.drop_index('ix_turn_records_thread_status', table_name='turn_records')
    op.drop_index('ix_turn_records_thread_sequence', table_name='turn_records')
    op.drop_table('turn_records')
    op.drop_index('ix_retrieval_token_lookup', table_name='retrieval_index_tokens')
    op.drop_index('ix_retrieval_token_entry', table_name='retrieval_index_tokens')
    op.drop_table('retrieval_index_tokens')
    op.drop_index('ix_retrieval_run_status', table_name='retrieval_index_runs')
    op.drop_index(op.f('ix_retrieval_index_runs_status'), table_name='retrieval_index_runs')
    op.drop_table('retrieval_index_runs')
    op.drop_index(op.f('ix_retrieval_candidates_run_id'), table_name='retrieval_candidates')
    op.drop_table('retrieval_candidates')
    op.drop_index('ix_retention_run_status', table_name='retention_cleanup_runs')
    op.drop_index(op.f('ix_retention_cleanup_runs_status'), table_name='retention_cleanup_runs')
    op.drop_table('retention_cleanup_runs')
    op.drop_index(op.f('ix_patch_operations_request_id'), table_name='patch_operations')
    op.drop_table('patch_operations')
    op.drop_index(op.f('ix_memory_maintenance_runs_status'), table_name='memory_maintenance_runs')
    op.drop_index('ix_maintenance_run_scope_status', table_name='memory_maintenance_runs')
    op.drop_table('memory_maintenance_runs')
    op.drop_index(op.f('ix_memory_lineage_successor_id'), table_name='memory_lineage')
    op.drop_index(op.f('ix_memory_lineage_predecessor_id'), table_name='memory_lineage')
    op.drop_table('memory_lineage')
    op.drop_index(op.f('ix_memory_evidence_memory_id'), table_name='memory_evidence')
    op.drop_table('memory_evidence')
    op.drop_index(op.f('ix_mcp_install_records_capability_id'), table_name='mcp_install_records')
    op.drop_table('mcp_install_records')
    op.drop_index(op.f('ix_llm_calls_trace_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_thread_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_table('forget_tombstones')
    op.drop_table('forget_targets')
    op.drop_table('forget_stage_runs')
    op.drop_table('forget_shields')
    op.drop_table('forget_selector_manifests')
    op.drop_table('forget_batches')
    op.drop_index('ix_events_turn_order', table_name='events')
    op.drop_index(op.f('ix_events_trace_id'), table_name='events')
    op.drop_index(op.f('ix_events_thread_id'), table_name='events')
    op.drop_index('ix_events_thread_created', table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_index('ix_epochs_thread_status', table_name='epochs')
    op.drop_index(op.f('ix_epochs_thread_id'), table_name='epochs')
    op.drop_table('epochs')
    op.drop_index('ix_snapshots_trace', table_name='context_snapshots')
    op.drop_index('ix_snapshots_thread_retention', table_name='context_snapshots')
    op.drop_index(op.f('ix_context_snapshots_trace_id'), table_name='context_snapshots')
    op.drop_index(op.f('ix_context_snapshots_thread_id'), table_name='context_snapshots')
    op.drop_table('context_snapshots')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_capability_versions_capability_id'), table_name='capability_versions')
    op.drop_table('capability_versions')
    op.drop_index(op.f('ix_artifacts_thread_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_ref'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('threads')
    op.drop_index(op.f('ix_tasks_thread_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_next_check_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_selfdev_requests_trace_id'), table_name='selfdev_requests')
    op.drop_table('selfdev_requests')
    op.drop_index(op.f('ix_segment_summaries_segment_id'), table_name='segment_summaries')
    op.drop_table('segment_summaries')
    op.drop_table('retrieval_runs')
    op.drop_table('retrieval_index_generations')
    op.drop_index('uq_retrieval_entry_current', table_name='retrieval_index_entries', postgresql_where=sa.text('is_current IS TRUE'), sqlite_where=sa.text('is_current = 1'))
    op.drop_index('ix_retrieval_entry_tier', table_name='retrieval_index_entries')
    op.drop_index('ix_retrieval_entry_thread', table_name='retrieval_index_entries')
    op.drop_index('ix_retrieval_entry_scope', table_name='retrieval_index_entries')
    op.drop_index('ix_retrieval_entry_active', table_name='retrieval_index_entries')
    op.drop_table('retrieval_index_entries')
    op.drop_index('ix_outbox_migration_batch', table_name='outbox_jobs')
    op.drop_index(op.f('ix_outbox_jobs_trace_id'), table_name='outbox_jobs')
    op.drop_index(op.f('ix_outbox_jobs_status'), table_name='outbox_jobs')
    op.drop_index(op.f('ix_outbox_jobs_operation_id'), table_name='outbox_jobs')
    op.drop_index(op.f('ix_outbox_jobs_job_type'), table_name='outbox_jobs')
    op.drop_index('ix_outbox_claim', table_name='outbox_jobs')
    op.drop_table('outbox_jobs')
    op.drop_index(op.f('ix_memory_records_scope_type'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_memory_type'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_memory_key'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_lifecycle_state'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_canonical_key'), table_name='memory_records')
    op.drop_table('memory_records')
    op.drop_index(op.f('ix_memory_recall_runs_trace_id'), table_name='memory_recall_runs')
    op.drop_table('memory_recall_runs')
    op.drop_index(op.f('ix_memory_recall_candidates_run_id'), table_name='memory_recall_candidates')
    op.drop_index(op.f('ix_memory_recall_candidates_memory_id'), table_name='memory_recall_candidates')
    op.drop_table('memory_recall_candidates')
    op.drop_index(op.f('ix_memory_proposals_proposal_id'), table_name='memory_proposals')
    op.drop_index(op.f('ix_memory_proposals_idempotency_key'), table_name='memory_proposals')
    op.drop_table('memory_proposals')
    op.drop_index(op.f('ix_forget_requests_memory_id'), table_name='forget_requests')
    op.drop_table('forget_requests')
    op.drop_table('forget_operations')
    op.drop_index(op.f('ix_epoch_checkpoints_epoch_id'), table_name='epoch_checkpoints')
    op.drop_table('epoch_checkpoints')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_core_memory_blocks_block_name'), table_name='core_memory_blocks')
    op.drop_table('core_memory_blocks')
    op.drop_index('ix_provenance_source', table_name='content_provenance_refs')
    op.drop_table('content_provenance_refs')
    op.drop_index(op.f('ix_capability_plans_status'), table_name='capability_plans')
    op.drop_table('capability_plans')
    op.drop_index(op.f('ix_capabilities_state'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_capability_id'), table_name='capabilities')
    op.drop_table('capabilities')
    op.drop_index(op.f('ix_attention_states_thread_id'), table_name='attention_states')
    op.drop_table('attention_states')
    # ### end Alembic commands ###
