"""V10: capabilities, capability_versions, mcp_install_records

Revision ID: a6575579d492
Revises: e482bbd77cd3
Create Date: 2026-07-07 19:47:04.545023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6575579d492'
down_revision: Union[str, Sequence[str], None] = 'e482bbd77cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('descriptor_hash', sa.String(length=32), nullable=True),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capabilities_capability_id'), 'capabilities', ['capability_id'], unique=True)
    op.create_index(op.f('ix_capabilities_state'), 'capabilities', ['state'], unique=False)
    op.create_table('capability_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('descriptor_hash', sa.String(length=32), nullable=False),
    sa.Column('tool_list_hash', sa.String(length=32), nullable=True),
    sa.Column('smoke_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_versions_capability_id'), 'capability_versions', ['capability_id'], unique=False)
    op.create_table('mcp_install_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('server_name', sa.String(length=256), nullable=False),
    sa.Column('package_ref', sa.String(length=256), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('transport', sa.String(length=32), nullable=False),
    sa.Column('declared_tools', sa.JSON(), nullable=False),
    sa.Column('sandbox_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_install_records_capability_id'), 'mcp_install_records', ['capability_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_install_records_capability_id'), table_name='mcp_install_records')
    op.drop_table('mcp_install_records')
    op.drop_index(op.f('ix_capability_versions_capability_id'), table_name='capability_versions')
    op.drop_table('capability_versions')
    op.drop_index(op.f('ix_capabilities_state'), table_name='capabilities')
    op.drop_index(op.f('ix_capabilities_capability_id'), table_name='capabilities')
    op.drop_table('capabilities')
    # ### end Alembic commands ###
