"""V16: retrieval_runs, retrieval_candidates

Revision ID: e46cc8625031
Revises: b4f1c7599b4c
Create Date: 2026-07-08 16:10:46.260332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46cc8625031'
down_revision: Union[str, Sequence[str], None] = 'b4f1c7599b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retrieval_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retrieval_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['retrieval_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_candidates_run_id'), 'retrieval_candidates', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retrieval_candidates_run_id'), table_name='retrieval_candidates')
    op.drop_table('retrieval_candidates')
    op.drop_table('retrieval_runs')
    # ### end Alembic commands ###
