"""V12: selfdev_requests, patch_operations

Revision ID: ec517a918616
Revises: a6575579d492
Create Date: 2026-07-08 15:35:38.110703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec517a918616'
down_revision: Union[str, Sequence[str], None] = 'a6575579d492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selfdev_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('source_event_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selfdev_requests_trace_id'), 'selfdev_requests', ['trace_id'], unique=False)
    op.create_table('patch_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('target_file', sa.String(length=512), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('risk_notes', sa.Text(), nullable=True),
    sa.Column('requires_schema_change', sa.Boolean(), nullable=False),
    sa.Column('safe_delete_scope', sa.String(length=64), nullable=True),
    sa.Column('not_allowed_yet', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['selfdev_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patch_operations_request_id'), 'patch_operations', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patch_operations_request_id'), table_name='patch_operations')
    op.drop_table('patch_operations')
    op.drop_index(op.f('ix_selfdev_requests_trace_id'), table_name='selfdev_requests')
    op.drop_table('selfdev_requests')
    # ### end Alembic commands ###
