"""V14: outbox_jobs

Revision ID: 0871550b7721
Revises: ec517a918616
Create Date: 2026-07-08 15:49:50.328894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0871550b7721'
down_revision: Union[str, Sequence[str], None] = 'ec517a918616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=128), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_jobs_job_type'), 'outbox_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_outbox_jobs_operation_id'), 'outbox_jobs', ['operation_id'], unique=True)
    op.create_index(op.f('ix_outbox_jobs_status'), 'outbox_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_jobs_trace_id'), 'outbox_jobs', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_jobs_trace_id'), table_name='outbox_jobs')
    op.drop_index(op.f('ix_outbox_jobs_status'), table_name='outbox_jobs')
    op.drop_index(op.f('ix_outbox_jobs_operation_id'), table_name='outbox_jobs')
    op.drop_index(op.f('ix_outbox_jobs_job_type'), table_name='outbox_jobs')
    op.drop_table('outbox_jobs')
    # ### end Alembic commands ###
