"""V20: attention_states

Revision ID: 2852f3b9cddd
Revises: cef6c7f626b3
Create Date: 2026-07-08 16:34:27.524316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2852f3b9cddd'
down_revision: Union[str, Sequence[str], None] = 'cef6c7f626b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attention_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('focus_topic', sa.String(length=256), nullable=True),
    sa.Column('recent_topics', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('suggestion', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attention_states_thread_id'), 'attention_states', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attention_states_thread_id'), table_name='attention_states')
    op.drop_table('attention_states')
    # ### end Alembic commands ###
