"""init: threads, events, llm_calls

Revision ID: 45cc16b9074c
Revises: 
Create Date: 2026-07-07 19:05:32.598894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45cc16b9074c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index('ix_events_thread_created', 'events', ['thread_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_events_thread_id'), 'events', ['thread_id'], unique=False)
    op.create_index(op.f('ix_events_trace_id'), 'events', ['trace_id'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('input_preview', sa.Text(), nullable=True),
    sa.Column('output_preview', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_thread_id'), 'llm_calls', ['thread_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_trace_id'), 'llm_calls', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_calls_trace_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_thread_id'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_events_trace_id'), table_name='events')
    op.drop_index(op.f('ix_events_thread_id'), table_name='events')
    op.drop_index('ix_events_thread_created', table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_table('threads')
    # ### end Alembic commands ###
