"""audit: memory_key, supersedes, superseded_by

Revision ID: 553f2bf14edf
Revises: 2852f3b9cddd
Create Date: 2026-07-08 17:23:57.567263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '553f2bf14edf'
down_revision: Union[str, Sequence[str], None] = '2852f3b9cddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memory_records', sa.Column('memory_key', sa.String(length=128), nullable=True))
    op.add_column('memory_records', sa.Column('revision', sa.Integer(), nullable=False))
    op.add_column('memory_records', sa.Column('supersedes', sa.String(length=36), nullable=True))
    op.add_column('memory_records', sa.Column('superseded_by', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_memory_records_memory_key'), 'memory_records', ['memory_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_records_memory_key'), table_name='memory_records')
    op.drop_column('memory_records', 'superseded_by')
    op.drop_column('memory_records', 'supersedes')
    op.drop_column('memory_records', 'revision')
    op.drop_column('memory_records', 'memory_key')
    # ### end Alembic commands ###
