"""V5: memory_records table

Revision ID: e482bbd77cd3
Revises: ef95c415d0ab
Create Date: 2026-07-07 19:25:28.316861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e482bbd77cd3'
down_revision: Union[str, Sequence[str], None] = 'ef95c415d0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('memory_type', sa.String(length=64), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_event_id', sa.String(length=36), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('lineage', sa.String(length=128), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_records_lifecycle_state'), 'memory_records', ['lifecycle_state'], unique=False)
    op.create_index(op.f('ix_memory_records_memory_type'), 'memory_records', ['memory_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_records_memory_type'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_lifecycle_state'), table_name='memory_records')
    op.drop_table('memory_records')
    # ### end Alembic commands ###
