"""V4: context_snapshots table

Revision ID: ef95c415d0ab
Revises: 45cc16b9074c
Create Date: 2026-07-07 19:13:01.790411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef95c415d0ab'
down_revision: Union[str, Sequence[str], None] = '45cc16b9074c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('stable_prefix_hash', sa.String(length=32), nullable=False),
    sa.Column('context_items', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_snapshots_thread_id'), 'context_snapshots', ['thread_id'], unique=False)
    op.create_index(op.f('ix_context_snapshots_trace_id'), 'context_snapshots', ['trace_id'], unique=False)
    op.create_index('ix_snapshots_trace', 'context_snapshots', ['trace_id', 'thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshots_trace', table_name='context_snapshots')
    op.drop_index(op.f('ix_context_snapshots_trace_id'), table_name='context_snapshots')
    op.drop_index(op.f('ix_context_snapshots_thread_id'), table_name='context_snapshots')
    op.drop_table('context_snapshots')
    # ### end Alembic commands ###
